version: '2'
services:
#  devotee-app:
#    container_name: user-app
#    build: ../devotee-app-angular
#    ports:
#      - "80:80"
#    depends_on:
#      - api-gateway
#    networks:
#      - back
  api-gateway:
    container_name: api-gateway
    build: ../api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - user-service
    networks:
      - back  
  user-service:
    container_name: user-service
    build: ../user-service
    depends_on:
      - mongo
    networks:
      - back 
  authentication-service:
    container_name: authentication-service
    build: ../authentication-service
    depends_on: 
      - mongo
    networks:
      - back       
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    #volumes:
    # - /data/db:/data/db
    networks:
      - back
networks:
  back:
    driver: bridge

