version: '2'
services:
  api-gateway:
    container_name: api-gateway
    image: parmar/api-gateway:latest
    ports:
      - "8000:8000"
    depends_on:
      - user-service
    networks:
      - back  
  devotee-service:
    container_name: user-service
    image: parmar/user-service:1.6
    depends_on:
      - mongo
    networks:
      - back 
  authentication-service:
    container_name: authentication-service
    image: parmar/authentication-service:1.6
    depends_on: 
      - mongo
    networks:
      - back       
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - /data/db:/data/db
    networks:
      - back
networks:
  back:
    driver: bridge

